### ISSUE TITLE
Crash using the Twisted verb

### ISSUE THREAD

**Issue by sanderbaan** [antoniotuzzi/nysthi#1]
Hi, just had a crash while using the twistedverb, was just turning some knobs and then it crashed. attached the crashlog for you
[rackcrash.txt](https://github.com/antoniotuzzi/nysthi/files/1379796/rackcrash.txt)

**Comment by antoniotuzzi** [comment]
thank you @sanderbaan ! Are you testing with a 0.4.0 Rack ?

**Comment by sanderbaan** [comment]
yes...i didnt had the most recent changes of 0.4.0 i updated to the latest state now and will see if i get the crash again.

**Comment by antoniotuzzi** [comment]
btw the crash is happening in the RACK code, but I can't say if is twistedreverb fault !
need Andrew help

**Comment by sanderbaan** [comment]
ok...let me see first if i am to reproduce it on the latest state...before we bother andrew ;)

**Comment by sanderbaan** [comment]
got it again, think is the same crash and was again with the twisted verb....added crashlog again, maybe you should ask andrew..

[rack crash2.txt](https://github.com/antoniotuzzi/nysthi/files/1380223/rack.crash2.txt)

**Comment by sanderbaan** [comment]
seems to be exactly the same crash

**Comment by antoniotuzzi** [comment]
is it just one particular knob ?
if yes, do you remember what's the one ?
and if you move the same knob on the other 2 reverb, you get the same crash ?
thank you !

**Comment by sanderbaan** [comment]
does not seem to be a specific knob, happens random...also i noticed that the right click context menu of twisted verb is also popping up randomly and pretty often while i dont click my right mouse button ;)

**Comment by sanderbaan** [comment]
and then the right click on that device does not work...super weird...maybe its the latest state of rack which has these issues

**Comment by sanderbaan** [comment]
when i then try to delete the twisted verb i have another crash, this time its different. see crashlog.
[rack crash3.txt](https://github.com/antoniotuzzi/nysthi/files/1380254/rack.crash3.txt)

**Comment by antoniotuzzi** [comment]
maybe a performance problem ? who knows
I run it on a Mac Book Pro 2012
OS Sierra 10.12.6
and you ?

**Comment by sanderbaan** [comment]
mac mini 2012 i7... also on 10.12.6 but had the crash also on 10.13

**Comment by sanderbaan** [comment]
when restarting rack after crash i get:
JSON parsing error at <stream> 133:4 ']' expected near end of file

another restart works fine again...

but only with your plugins i have these problems...did you try to rightclick on one of the modules with the latest 0.40? for me it does not work on any of the modules..i tried all other stock modules and the plugins from other peeps and they work fine..

**Comment by antoniotuzzi** [comment]
for me is everything ok
(the json error probably was due to a wrong autosaved file during a crash )

**Comment by sanderbaan** [comment]
super strange...if we are both running the same version of rack and plugins we should get the same issues...

**Comment by sanderbaan** [comment]
i talked to andrew...he says its probably a version mismatch..i used the 0.40 binary from the releases tab on github...could you maybe make a new one with the latest rack state because some drastic things have changed there probably causing these issues ;)

**Comment by antoniotuzzi** [comment]
AH! could be the reason! Yes it's not an official release (let's cross fingers...)

**Comment by antoniotuzzi** [comment]
I can't see any 0.4 tag under RACK ? Are you sure ?

**Comment by antoniotuzzi** [comment]
ok try with this 
[Rack.zip](https://github.com/antoniotuzzi/nysthi/files/1380428/Rack.zip)

**Comment by sanderbaan** [comment]
try compiling your plugins with the latest sourcecode of rack..

**Comment by sanderbaan** [comment]
trying :)

**Comment by sanderbaan** [comment]
cant start that one...

Last login: Thu Oct 12 21:24:42 on ttys001

betas-mbp:~ beta$ /Users/beta/Rack/Rack ; exit;

dyld: Library not loaded:
/Users/antoniotuzzi/Desktop/githubprojects/Rack/dep/lib/libcurl.4.dylib

  Referenced from: /Users/beta/Rack/Rack

  Reason: Incompatible library version: Rack requires version 9.0.0 or
later, but libcurl.4.dylib provides version 7.0.0

Abort trap: 6

logout

**Comment by sanderbaan** [comment]
i think if you compile the plugin with the latest sourcecode of rack and
then send me the plugin it will work

**Comment by antoniotuzzi** [comment]
I'm having problems, now for symbols not declared with last Rack download...

**Comment by antoniotuzzi** [comment]
almost there...

**Comment by antoniotuzzi** [comment]
use this in the nysthi folder
recompiled with all, last minute...
[plugin.dylib.zip](https://github.com/antoniotuzzi/nysthi/files/1380519/plugin.dylib.zip)
(unzip in the destination dir)

**Comment by sanderbaan** [comment]
yes working now ;)

**Comment by antoniotuzzi** [comment]
thank you very much for your efforts
I'm going to realign win10 and linux too... (what a pain in the ass, I don't care about them.. :D )

**Comment by sanderbaan** [comment]
no problem :) yes i guess this will be staying problematic until version
1.0.0 is out

**Comment by antoniotuzzi** [comment]
updated the release too
https://github.com/antoniotuzzi/nysthi/files/1380618/nysthi_v0.4.0.C.zip

**Comment by antoniotuzzi** [comment]
with the final release 0.4.0 this is closed! thanks!
