### ISSUE TITLE
win7 zip Download - Is the Dual Meter included?

### ISSUE THREAD

**Issue by Felnyrii** [antoniotuzzi/nysthi#12]
Hi Antonio, I have seen you post in the Facebook group regarding a Dual Meter and, for the life of me, I cannot seem to find the correct download that potentially includes it.

Either it was only promoted and not yet published or my own user error.

Side note: so far your plugins are the best thing in VCV for myself. LFO Multiphase 10/10

**Comment by antoniotuzzi** [comment]
are you downloading  from releases ?
https://github.com/antoniotuzzi/nysthi/releases
(there is always attached a file nysthi.zip )

**Comment by Felnyrii** [comment]
The top post is the most recent one I tried. Once I get back to the computer I will reinstall and see if it works.

**Comment by Felnyrii** [comment]
@antoniotuzzi 

Thanks, I redownloaded the .zip from the newest post and everything seems functional on my home computer. (win10)
