### ISSUE TITLE
LFO Multiphase - Waveform Blending / Morphing?

### ISSUE THREAD

**Issue by Felnyrii** [antoniotuzzi/nysthi#13]
As a suggestion or request, would it be possible to blend or morph between waveforms on the LFO Multiphase rather than simply selecting / hard switching? Perhaps CV over the waveform selection?

**Comment by antoniotuzzi** [comment]
I can put a crossfading, not a morph
but would be fine

**Comment by Felnyrii** [comment]
That would be awesome.

**Comment by antoniotuzzi** [comment]
I have it... next release :D

**Comment by Felnyrii** [comment]
Great job, Antonio! I look forward to trying it!
